name: amia
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.13
  - pip
  - openbabel
  - autodock-vina
  - pymol-open-source
  - pip:
      - click>=8.1
      - PyYAML>=6.0
      - biopython>=1.79
      - MDAnalysis[analysis]>=2.4.0
      - MDAnalysisTests
      - pandas>=1.5.3
      - numpy>=1.24.2
      - scipy>=1.10.0
      - matplotlib>=3.7.0
      - networkx>=3.0
      - plotly>=5.0