# Project Title: "The development of an automated computational workflow to prioritize potential resistance variants identified in HIV Integrase Subtype C"
# This script is developed for the fufuillment for Masters at the South African National Bioinformatics Institute at the University of the Western Cape
# The project is funded by the Poliomyelitis Research Foundation and the UWC Ada & Bertie Levenstein Bursary Programme
# Currently any licensing and usage of this software is governed under the regulations of the afore mentioned parties

# Author:	Keaghan Brown (3687524) - MSc Bioinformatics Candidate (3687524@myuwc.ac.za)
# Author:	Ruben Cloete (Supervisor) - Lecturer at South African National Bioinformatics Institute (ruben@sanbi.ac.za)


import MDAnalysis as mda
from MDAnalysis.tests.datafiles import XTC, TPR
from MDAnalysis.analysis import contacts
from MDAnalysis.analysis.hydrogenbonds import HydrogenBondAnalysis
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import os, argparse
import datetime

class Contacts:

    def contacts_within_cutoff(self, u, group_a, group_b, radius=3.5):
        """The MDAnalysis package allows a user to iterate through every frame of the trajetcory and calculate the
        number of contacts between two selections of atoms within a specified distance. The contacts are then stored
        as a list of lists and returned for further processing."""
        timeseries = []
        for ts in u.trajectory:
            dist = contacts.distance_array(group_a.positions, group_b.positions)
            n_contacts = contacts.contact_matrix(dist, radius).sum()
            timeseries.append([ts.frame, n_contacts])
        return np.array(timeseries)

    def saltbridges(self, top_file, traj_file):
        """Saltbridges or ionic bonds occur between acidic and basic residues within the protein structure. Here the
        residues and the respective atoms involved are selected and passed to the contacts within cutoff function,
        and returned as a dataframe which is then stored within the original system folder as a .csv file
        for figure generation."""
        u = mda.Universe(top_file, traj_file)
        sel_basic = "(resname ARG LYS) and (name NH* NZ)"
        sel_acidic = "(resname ASP GLU) and (name OE* OD*)"
        basic = u.select_atoms(sel_basic)
        acidic = u.select_atoms(sel_acidic)
        ca = self.contacts_within_cutoff(u, basic, acidic, radius=4.5)
        ca_df = pd.DataFrame(ca, columns=['Time (ns)', str(top_file).split('.')[0]])
        ca_df['Time (ns)'] = ca_df['Time (ns)']/10
        ca_df.to_csv(str(top_file.split('.')[0] + '_salt_bridges.csv'))
        return ca_df

    def saltbridges_comp(self, traj_folder, output_dir):
        """This fucntion iterates through each of the systems that were simulated and calls the saltbridges
        function to determine the respective contacts. Each of the salt bridges for each of the system under
        investigation have their .csv retreived and appended to a new dataframe for ease of comparison between the
        systems, which is then stored in the output specified folder."""
        df = pd.DataFrame()
        for folder in os.listdir(traj_folder):
            top_file = ''
            traj_file = ''
            os.chdir('{0}/{1}'.format(str(traj_folder), folder))
            for file in os.listdir():
                if file.endswith('.xtc') and 'rmsfit_' not in str(file):
                    traj_file = file
                elif file.endswith('.tpr'):
                    top_file = file
            sb_df = self.saltbridges(top_file, traj_file)
            if df.empty:
                df = pd.concat([df, sb_df], axis=1)
            else:
                df = pd.merge(df, sb_df, on = 'Time (ns)', how='inner')
        os.chdir(output_dir)
        df.to_csv('multi_variant_saltbridges.csv')

    def multi_sb_plotting(self, outputs_dir, start_fr):
        """This function plots the multi-variant.csv file generated by the saltbridges_comp function from within the
        previously defined output directory and creates a figure with each dataset present within the file. This
        function was developed prior to the single plot generation, however too many datasets resulted in degraded
        visualization."""
        os.chdir(outputs_dir)
        for file in os.listdir(outputs_dir):
            if file.endswith('multi_variant_saltbridges.csv'):
                sb_df = pd.read_csv(file)
                sb_df['Time (ns)'] = sb_df['Time (ns)']
                sb_df.iloc[int(start_fr):, 1:len(sb_df)].plot(x='Time (ns)', linewidth=0.5)
                plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
                plt.title('Multi-system Protein-Protein Ionic Interactions')
                plt.ylabel(r"$N_{II}$")
                plt.savefig('{0}/{1}{2}'.format(str(outputs_dir), str(file).split('.')[0], '.tiff'),
                            bbox_inches='tight', dpi=600)


    def hbond_calc(self, top_file, traj_file, start_fr):
        """Currently the set of ions and solvent ions have been predefined for this function and will need to be
        expanded upon for further diversity in molecular analyses. Here the script iterates through each of the
        segments within a universe created using the trajectory and topology files. The script then looks for segments
        that are not metalic ions, solvent ions or other protein segments and calculates the h-bonds present between the
        entire protein atom selection as well as all the atoms present in the filtered segments. This results in a
        function which is currently abe to identify the ligand and Nucleic Acid present within the system and execute the
        respective anallysis and return the stored results as a dataframe for each of the systems."""
        solvent_mol = ['POT', 'TIP3', "CLA"]
        ions = ['H', 'HE', 'LI', 'BE', 'B', 'C', 'N', 'O', 'F', 'NE', 'NA', 'MG', 'AL', 'SI', 'P', 'S', 'CL', 'AR', 'K', 'CA',
         'SC', 'TI', 'V', 'CR', 'MN', 'FE', 'CO', 'NI', 'CU', 'ZN', 'ZN2','GA', 'GE', 'AS', 'SE', 'BR', 'KR', 'RB', 'SR', 'Y',
         'ZR', 'NB', 'MO', 'TC', 'RU', 'RH', 'PD', 'AG', 'CD', 'IN', 'SN', 'SB', 'TE', 'I', 'XE', 'CS', 'BA', 'LA',
         'CE', 'PR', 'ND', 'PM', 'SM', 'EU', 'GD', 'TB', 'DY', 'HO', 'ER', 'TM', 'YB', 'LU', 'HF', 'TA', 'W', 'RE',
         'OS', 'IR', 'PT', 'AU', 'HG', 'TL', 'PB', 'BI', 'PO', 'AT', 'RN', 'FR', 'RA', 'AC', 'TH', 'PA', 'U', 'NP',
         'PU', 'AM', 'CM', 'BK', 'CF', 'ES', 'FM', 'MD', 'NO', 'LR', 'RF', 'DB', 'SG', 'BH', 'HS', 'MT', 'DS', 'RG',
         'CN', 'NH', 'FL', 'MC', 'LV', 'TS', 'OG']

        mols = []
        u = mda.Universe(traj_file, top_file)
        hbonds_df = pd.DataFrame()
        df = pd.DataFrame()
        for seg in u.segments:
            if 'PRO' not in str(seg) and str(seg)[1:-1].split(' ')[1].split('_')[2] not in solvent_mol and \
                    str(seg)[1:-1].split(' ')[1].split('_')[2] not in ions and 'DNA' not in str(seg) and 'RNA' not in str(seg):
                hbonds = HydrogenBondAnalysis(universe=u, d_a_cutoff=4.5,  update_selections=False)
                hbonds.hydrogens_sel = hbonds.guess_hydrogens("protein")
                hbonds.acceptors_sel = hbonds.guess_acceptors("segid " + str(seg)[1:-1].split(' ')[1])
                hbonds.run(verbose=True, start=int(start_fr))
                df1 = pd.DataFrame(hbonds.times, columns=['Time (ns)'])
                df2 = pd.DataFrame(hbonds.count_by_time(), columns=[str(top_file).split('.')[0]])
                df = pd.concat([df1, df2], axis=1)
                df.to_csv(str(seg)[1:-1].split(' ')[1].split('_')[2] + '_hbonds.csv')
                hbonds_df = pd.concat([hbonds_df, df], axis=1)

    def nucleic_prot_hbonds(self, top_file, traj_file, start_fr):
        u = mda.Universe(traj_file, top_file)
        hbonds_df = pd.DataFrame()
        df = pd.DataFrame()
        hbonds = HydrogenBondAnalysis(universe=u, d_a_cutoff=3.5, update_selections=True)
        hbonds.hydrogens_sel = hbonds.guess_hydrogens("protein")
        hbonds.acceptors_sel = hbonds.guess_acceptors("nucleic")
        hbonds.run(verbose=True, start=int(start_fr))
        df1 = pd.DataFrame(hbonds.times, columns=['Time (ns)'])
        df2 = pd.DataFrame(hbonds.count_by_time(), columns= [str(top_file).split('.')[0] +  str(' Nucleic Acid ')])
        nucleic_df = pd.concat([df1, df2], axis=1)
        nucleic_df.to_csv('nucleic_hbonds.csv')

    def hbond_comp(self, traj_folder, output_dir, start_fr):
        """This fucntion iterates through each of the systems that were simulated and calls the hbonds
        function to determine the respective contacts. Each of the hbonds for each of the systems under
        investigation have their hbonds.csv retrieved and each of the columns at the respective positions
        (each column correlates to the same molecule investigated) and appended to a new dataframe for ease of
        comparison between the systems, which is then stored in the output specified folder."""
        df = pd.DataFrame()
        for folder in os.listdir(traj_folder):
            top_file = ''
            traj_file = ''
            os.chdir('{0}/{1}'.format(str(traj_folder), folder))
            for file in os.listdir():
                if file.endswith('.xtc') and 'rmsfit_' not in str(file):
                    traj_file = file
                elif file.endswith('.tpr'):
                    top_file = file
            # sys_hbonds = self.hbond_calc(traj_file, top_file, start_fr)
            sys_nucleic_hbonds = self.nucleic_prot_hbonds(traj_file, top_file, start_fr)


    def multi_hbonds_plots(self, outputs_dir, start_df):
        """This function plots the 'multi-variant_hbonds'.csv file generated by the hbonds_comp function from within the
        previously defined output directory and creates a figure with each dataset present within the file. This
        function was developed prior to the single plot generation, however too many datasets resulted in degraded
        visualization."""
        solvent_mol = ['POT', 'TIP3', "CLA"]
        ions = ['H', 'HE', 'LI', 'BE', 'B', 'C', 'N', 'O', 'F', 'NE', 'NA', 'MG', 'AL', 'SI', 'P', 'S', 'CL', 'AR', 'K', 'CA',
         'SC', 'TI', 'V', 'CR', 'MN', 'FE', 'CO', 'NI', 'CU', 'ZN', 'ZN2','GA', 'GE', 'AS', 'SE', 'BR', 'KR', 'RB', 'SR', 'Y',
         'ZR', 'NB', 'MO', 'TC', 'RU', 'RH', 'PD', 'AG', 'CD', 'IN', 'SN', 'SB', 'TE', 'I', 'XE', 'CS', 'BA', 'LA',
         'CE', 'PR', 'ND', 'PM', 'SM', 'EU', 'GD', 'TB', 'DY', 'HO', 'ER', 'TM', 'YB', 'LU', 'HF', 'TA', 'W', 'RE',
         'OS', 'IR', 'PT', 'AU', 'HG', 'TL', 'PB', 'BI', 'PO', 'AT', 'RN', 'FR', 'RA', 'AC', 'TH', 'PA', 'U', 'NP',
         'PU', 'AM', 'CM', 'BK', 'CF', 'ES', 'FM', 'MD', 'NO', 'LR', 'RF', 'DB', 'SG', 'BH', 'HS', 'MT', 'DS', 'RG',
         'CN', 'NH', 'FL', 'MC', 'LV', 'TS', 'OG']
        sys_hetatms = []
        hetatm_file_pair = {}
        for system in os.listdir(systems):
            top_file = ''
            traj_file = ''
            os.chdir('{0}/{1}'.format(str(systems), system))
            for file in os.listdir():
                if file.endswith('.xtc') and 'rmsfit_' not in str(file):
                    traj_file = file
                elif file.endswith('.tpr'):
                    top_file = file
            u = mda.Universe(top_file, traj_file)
            for seg in u.segments:
                if 'PRO' not in str(seg) and str(seg)[1:-1].split(' ')[1].split('_')[2] not in solvent_mol and str(seg)[1:-1].split(' ')[1].split('_')[2] not in ions and 'DNA' not in str(seg) and 'RNA' not in str(seg):
                    hetatm = str(seg).split(' ')[1].split('_')[-1][:-1]
                    if hetatm not in sys_hetatms:
                        sys_hetatms.append(hetatm)
        for hetatm in sys_hetatms:
            for system in os.listdir(systems):
                os.chdir('{0}/{1}'.format(str(systems), system))
                for sys_file in os.listdir():
                    if str(hetatm) in str(sys_file) and 'hbonds.csv' in str(sys_file):
                         hetatm_file_pair.setdefault(hetatm, []).append('{0}/{1}'.format(str(os.getcwd()), sys_file))
        for key in hetatm_file_pair:
            df = pd.DataFrame()
            for hetatm_data in hetatm_file_pair[key]:
                hetatm_df = pd.read_csv(hetatm_data)
                hetatm_df['Time (ns)'] =  hetatm_df['Time (ns)']/1000
                if df.empty == True:
                    df = hetatm_df.iloc[:,1:]
                else:
                    df = pd.concat([df, hetatm_df.iloc[:, -1]], axis=1)
            df.plot(x='Time (ns)', linewidth=0.5)
            plt.title('Multi-system Protein-'  + str(key) + ' H-bonds')
            plt.ylabel(r"$N_{HB}$")
            plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
            plt.savefig('{0}/{1}'.format(str(output_dir), 'Multi-system Protein-'  + str(key) + '_hbonds.tiff'), bbox_inches='tight', dpi=900)

    def multi_nucleic_hbonds_plots(self, outputs_dir, start_df):
        """This function plots the 'multi-variant_hbonds'.csv file generated by the hbonds_comp function from within the
        previously defined output directory and creates a figure with each dataset present within the file. This
        function was developed prior to the single plot generation, however too many datasets resulted in degraded
        visualization."""
        solvent_mol = ['POT', 'TIP3', "CLA"]
        ions = ['H', 'HE', 'LI', 'BE', 'B', 'C', 'N', 'O', 'F', 'NE', 'NA', 'MG', 'AL', 'SI', 'P', 'S', 'CL', 'AR', 'K', 'CA',
         'SC', 'TI', 'V', 'CR', 'MN', 'FE', 'CO', 'NI', 'CU', 'ZN', 'ZN2','GA', 'GE', 'AS', 'SE', 'BR', 'KR', 'RB', 'SR', 'Y',
         'ZR', 'NB', 'MO', 'TC', 'RU', 'RH', 'PD', 'AG', 'CD', 'IN', 'SN', 'SB', 'TE', 'I', 'XE', 'CS', 'BA', 'LA',
         'CE', 'PR', 'ND', 'PM', 'SM', 'EU', 'GD', 'TB', 'DY', 'HO', 'ER', 'TM', 'YB', 'LU', 'HF', 'TA', 'W', 'RE',
         'OS', 'IR', 'PT', 'AU', 'HG', 'TL', 'PB', 'BI', 'PO', 'AT', 'RN', 'FR', 'RA', 'AC', 'TH', 'PA', 'U', 'NP',
         'PU', 'AM', 'CM', 'BK', 'CF', 'ES', 'FM', 'MD', 'NO', 'LR', 'RF', 'DB', 'SG', 'BH', 'HS', 'MT', 'DS', 'RG',
         'CN', 'NH', 'FL', 'MC', 'LV', 'TS', 'OG']
        sys_hetatms = []
        hetatm_file_pair = {}
        df = pd.DataFrame()
        for system in os.listdir(systems):
            os.chdir('{0}/{1}'.format(str(systems), system))
            for file in os.listdir():
                if str('nucleic') in str(file) and 'hbonds.csv' in str(file):
                    nucleic_hbonds_df = pd.read_csv(file)
                    nucleic_hbonds_df['Time (ns)'] = nucleic_hbonds_df['Time (ns)']/1000
                    if df.empty == True:
                        df = nucleic_hbonds_df.iloc[:,1:]
                    else:
                        df = pd.concat([df, nucleic_hbonds_df.iloc[:,2:]], axis=1)
            os.chdir(systems)
        df.plot(x='Time (ns)', linewidth=0.5)
        plt.title('Multi-system Protein-Nucelic Acid H-bonds')
        plt.ylabel(r"$N_{HB}$")
        plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
        plt.savefig('{0}/{1}'.format(str(output_dir), 'Multi-system Protein-Nucleic_Acid_hbonds.tiff'), bbox_inches='tight', dpi=900)

    def hetatm_calc(self, top_file, traj_file, start_fr):
        print(datetime.datetime.now())
        mols = []
        solvent_mol = ['POT', 'TIP3', 'CLA']
        hbonds_df = pd.DataFrame()
        u = mda.Universe(top_file, traj_file)
        for seg in u.segments:
            if 'PRO' not in str(seg) and str(seg)[1:-1].split(' ')[1].split('_')[2] not in solvent_mol and 'DNA' not in str(seg) and 'RNA' not in str(seg):
                mols.append(str(seg).split(' ')[1][:-1])
        for mol in mols:
            for mol2 in mols:
                if mol != mol2:
                    hbonds = HydrogenBondAnalysis(universe=u, d_a_cutoff=4.5, update_selections=True)
                    hbonds.hydrogens_sel = hbonds.guess_hydrogens('segid ' + str(mol))
                    hbonds.acceptors_sel = hbonds.guess_acceptors('segid ' + str(mol2))
                    hbonds.run(verbose=True, start=int(start_fr))
                    df1 = pd.DataFrame(hbonds.times, columns=['Time (ns)'])
                    df2 = pd.DataFrame(hbonds.count_by_time(), columns=[str(top_file).split('.')[0]])
                    df = pd.concat([df1, df2], axis=1)
                    df.to_csv(str(mol) + str(mol2) + '_hetatm_hbonds.csv')
                    hbonds_df = pd.concat([hbonds_df, df], axis=1)
            mols.remove(mol)

    def hetatm_conts(self, traj_folder, start_fr):
        for folder in os.listdir(traj_folder):
            top_file = ''
            traj_file = ''
            os.chdir('{0}/{1}'.format(str(traj_folder), folder))
            for file in os.listdir():
                if file.endswith('.xtc') and 'rmsfit_' not in str(file):
                    traj_file = file
                elif file.endswith('.tpr'):
                    top_file = file
            self.hetatm_calc(top_file, traj_file, start_fr)

    def hetatm_plot(self, systems, outputs_dir, start_fr):
        os.chdir(systems)
        system_hetatm_conts = {}
        for folder in os.listdir(systems):
            os.chdir(folder)
            for file in os.listdir():
                if file.endswith('hetatm_contacts.csv'):
                    system_hetatm_conts.setdefault(folder, []).append('{0}/{1}'.format(str(os.getcwd()), file))
            os.chdir(systems)
        for key in system_hetatm_conts:
            contact_sys = len(system_hetatm_conts[key])
            for i in range(contact_sys):
                df = pd.DataFrame()
                for key in system_hetatm_conts:
                    title_hetatm = str(os.path.basename(system_hetatm_conts[key][i])).split('_')[1:3]
                    hetatm_df = pd.read_csv(system_hetatm_conts[key][i])
                    if df.empty == True:
                        df = hetatm_df.iloc[8000:,1:]
                    else:
                        df = pd.concat([df, hetatm_df.iloc[8000:, -1]], axis=1)
                df.plot(x='Time (ns)', linewidth=0.5)
                plt.title('Multi-system ' + str(title_hetatm[0]) + '-'+ str(title_hetatm[1]) + ' interactions')
                plt.ylabel(r"$N_{II}$")
                plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
                plt.savefig('{0}/{1}{2}'.format(outputs_dir, 'Multi-system ' + str(title_hetatm[0])+str(title_hetatm[1]), ' interactions.tiff'), bbox_inches='tight', dpi=900)

    def nucleic_saltbridges_calc(self, top_file, traj_file):
        """Saltbridges or ionic bonds occur between acidic and basic residues within the protein structure. Here the
        residues and the respective atoms involved are selected and passed to the contacts within cutoff function,
        and returned as a dataframe which is then stored within the original system folder as a .csv file
        for figure generation."""
        u = mda.Universe(top_file, traj_file)
        sel_basic = "(resname ARG LYS) and (name NH* NZ)"
        sel_acidic = "nucleic and (name *P)"
        group1 = u.select_atoms(sel_basic)
        group2 = u.select_atoms(sel_acidic)
        ca = self.contacts_within_cutoff(u, group1, group2, radius=4.5)
        ca_df = pd.DataFrame(ca, columns=['Time (ns)', str(top_file).split('.')[0]])
        ca_df['Time (ns)'] = ca_df['Time (ns)'] /10
        ca_df.to_csv(str(top_file.split('.')[0] + '_Nucleic_Acid_saltbridges.csv'))

    def nucleic_ionic_conts(self, traj_folder):
        for folder in os.listdir(traj_folder):
            top_file = ''
            traj_file = ''
            os.chdir('{0}/{1}'.format(str(traj_folder), folder))
            for file in os.listdir():
                if file.endswith('.xtc') and 'rmsfit_' not in str(file):
                    traj_file = file
                elif file.endswith('.tpr'):
                    top_file = file
            self.nucleic_saltbridges_calc(top_file, traj_file)

    def ionic_nucleic_plot(self, systems, outputs_dir, start_fr):
        os.chdir(systems)
        multi_df = pd.DataFrame()
        for folder in os.listdir(systems):
            os.chdir(folder)
            for file in os.listdir():
                if file.endswith('Nucleic_Acid_saltbridges.csv'):
                    heading = str(file).split('.')[0].split('_')
                    title = heading[0] + ' ' + heading[1] + '-' + heading[2]
                    ionic_nucleic_df = pd.read_csv(file)
                    ionic_nucleic_df = ionic_nucleic_df.iloc[int(start_fr):, 1:]
                    if multi_df.empty == True:
                        multi_df = ionic_nucleic_df
                    else:
                        multi_df = pd.concat([multi_df, ionic_nucleic_df.iloc[:,1]], axis=1)
            os.chdir(systems)
        multi_df.plot(x='Time (ns)', linewidth=0.5)
        plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
        plt.ylabel(r"$N_{II}$")
        plt.title('Multi-system Protein-Nucleic Ionic Interactions')
        plt.savefig('{0}/{1}{2}'.format(outputs_dir, 'Multi-system Protein-Nucleic Ionic Interactions', '.tiff'), bbox_inches='tight', dpi=900)

def main(systems, output_dir, start_fr):
    p = Contacts()
    p.saltbridges_comp(systems, output_dir)
    p.multi_sb_plotting(output_dir, start_fr)
    p.hbond_comp(systems, output_dir, start_fr)
    p.multi_hbonds_plots(output_dir, start_fr)
    p.multi_nucleic_hbonds_plots(output_dir, start_fr)
    p.hetatm_conts(systems, start_fr)
    p.hetatm_plot(systems, output_dir, start_fr)
    p.nucleic_ionic_conts(systems)
    p.ionic_nucleic_plot(systems, output_dir, start_fr)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--systems", help="Path to the trajectory files have been simulated. ")
    parser.add_argument("--output_dir", help="Path to the directory that the variant systems will be stored in")
    args = parser.parse_args()
    systems = str(args.systems)
    output_dir = str(args.output_dir)
    start_fr = input("Enter starting frame of trajectory equilibration:")
    main(systems, output_dir, start_fr)
