# Project Title: "Automated computational workflow to prioritize potential resistance variants identified in HIV Integrase Subtype C and CRF02_AG"
# This script is developed for the fufuillment for Masters at the South African National Bioinformatics Institute at the University of the Western Cape
# The project is funded by the Poliomyelitis Research Foundation and the UWC Ada & Bertie Levenstein Bursary Programme
# Currently any licensing and usage of this software is governed under the regulations of the afore mentioned parties

# Author:	Keaghan Brown (3687524) - MSc Bioinformatics Candidate (3687524@myuwc.ac.za)
# Author:	Ruben Cloete (Supervisor) - Lecturer at South African National Bioinformatics Institute (ruben@sanbi.ac.za)


import MDAnalysis as mda
from MDAnalysis.tests.datafiles import XTC, TPR
from MDAnalysis.analysis import contacts
from MDAnalysis.analysis.hydrogenbonds import HydrogenBondAnalysis
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import os, argparse

class Contacts:


	def contacts_within_cutoff(self, u, group_a, group_b, radius=3.5):
		"""The MDAnalysis package allows a user to iterate through every frame of the trajetcory and calculate the
		number of contacts between two selections of atoms within a specified distance. The contacts are then stored
		as a list of lists and returned for further processing."""
		timeseries = []
		for ts in u.trajectory:
			dist = contacts.distance_array(group_a.positions, group_b.positions)
			n_contacts = contacts.contact_matrix(dist, radius).sum()
			timeseries.append([ts.frame, n_contacts])
		return np.array(timeseries)

	def saltbridges(self, top_file, traj_file):
		"""Saltbridges or ionic bonds occur between acidic and basic residues within the protein structure. Here the
		residues and the respective atoms involved are selected and passed to the contacts within cutoff function,
		and returned as a dataframe which is then stored within the original system folder as a .csv file
		for figure generation."""
		u = mda.Universe(top_file, traj_file)
		sel_basic = "(resname ARG LYS) and (name NH* NZ)"
		sel_acidic = "(resname ASP GLU) and (name OE* OD*)"
		basic = u.select_atoms(sel_basic)
		acidic = u.select_atoms(sel_acidic)
		ca = self.contacts_within_cutoff(u, basic, acidic, radius=4.5)
		ca_df = pd.DataFrame(ca, columns=['Time (ns)', str(top_file).split('.')[0] + ' No. of Contacts'])
		ca_df['Time (ns)'] = ca_df['Time (ns)']/10
		ca_df.to_csv(str(top_file.split('.')[0] + '_salt_bridges.csv'))
		return ca_df

	def saltbridges_comp(self, traj_folder, output_dir):
		"""This fucntion iterates through each of the systems that were simulated and calls the saltbridges
		function to determine the respective contacts. Each of the salt bridges for each of the system under
		investigation have their .csv retreived and appended to a new dataframe for ease of comparison between the
		systems, which is then stored in the output specified folder."""
		df = pd.DataFrame()
		for folder in os.listdir(traj_folder):
			top_file = ''
			traj_file = ''
			os.chdir('{0}\{1}'.format(str(traj_folder), folder))
			for file in os.listdir():
				if file.endswith('.xtc') and 'rmsfit_' not in str(file):
					traj_file = file
				elif file.endswith('.tpr'):
					top_file = file
			sb_df = self.saltbridges(top_file, traj_file)
			if df.empty:
				df = pd.concat([df, sb_df], axis=1)
			else:
				df = pd.merge(df, sb_df, on = 'Time (ns)', how='inner')
		os.chdir(output_dir)
		df.to_csv('multi_variant_saltbridges.csv')

	def single_sb_plotting(self, traj_folder,outputs_dir):
		"""The first saltbridge figure function iterates over each of the systems individually and reads the
		saltbridge.csv files previously generated and plots them using matplotlib afterwhich the figure is saved to the
		specified output directory. This was included along with the option to have multiple plots on a single set of
		axes as it became difficult to interpret the results with the more systems present."""
		for folder in os.listdir(traj_folder):
			os.chdir('{0}\{1}'.format(str(traj_folder), folder))
			for file in os.listdir():
				if file.endswith('_salt_bridges.csv'):
					df = pd.read_csv(file)
					df['Time (ns)'] = df['Time (ns)'] / 10
					df2 = df.iloc[:, 1:len(df)]
					df2.plot(x='Time (ns)', linewidth=0.75)
					plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
					plt.title(
						'No. of Salt Bridges within ' + str(file).split('.')[0] + ' systems')
					plt.savefig('{0}\{1}{2}'.format(str(outputs_dir), str(file).split('.')[0], '.tiff'),
								bbox_inches='tight', dpi=600)

	def multi_sb_plotting(self, outputs_dir):
		"""This function plots the multi-variant.csv file generated by the saltbridges_comp function from within the
		previously defined output directory and creates a figure with each dataset present within the file. This
		function was developed prior to the single plot generation, however too many datasets resulted in degraded
		visualization."""
		os.chdir(outputs_dir)
		for file in os.listdir(outputs_dir):
			if file.endswith('multi_variant_saltbridges.csv'):
				sb_df = pd.read_csv(file)
				sb_df['Time (ns)'] = sb_df['Time (ns)']/10
				sb_df.iloc[:, 1:len(sb_df)].plot(x='Time (ns)', linewidth=0.75)
				plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
				plt.title(
					'No. of Salt Bridges within variant systems')
				plt.savefig('{0}\{1}{2}'.format(str(outputs_dir), str(file).split('.')[0], '.tiff'),
							bbox_inches='tight', dpi=600)


	def hbond_calc(self, top_file, traj_file):
		"""Currently the set of ions and solvent ions have been predefined for this function and will need to be
		expanded upon for further diversity in molecular analyses. Here the script iterates through each of the
		segments within a universe created using the trajectory and topology files. The script then looks for segments
		that are not metalic ions, solvent ions or other protein segments and calculates the h-bonds present between the
		entire protein atom selection as well as all the atoms present in the filtered segments. This results in a
		function which is currently abe to identify the ligand and DNA present within the system and execute the
		respective anallysis and return the stored results as a dataframe for each of the systems."""
		solvent_mol = ['POT', 'TIP3', "CLA"]
		ions = ['H', 'HE', 'LI', 'BE', 'B', 'C', 'N', 'O', 'F', 'NE', 'NA', 'MG', 'AL', 'SI', 'P', 'S', 'CL', 'AR', 'K', 'CA',
		 'SC', 'TI', 'V', 'CR', 'MN', 'FE', 'CO', 'NI', 'CU', 'ZN', 'ZN2','GA', 'GE', 'AS', 'SE', 'BR', 'KR', 'RB', 'SR', 'Y',
		 'ZR', 'NB', 'MO', 'TC', 'RU', 'RH', 'PD', 'AG', 'CD', 'IN', 'SN', 'SB', 'TE', 'I', 'XE', 'CS', 'BA', 'LA',
		 'CE', 'PR', 'ND', 'PM', 'SM', 'EU', 'GD', 'TB', 'DY', 'HO', 'ER', 'TM', 'YB', 'LU', 'HF', 'TA', 'W', 'RE',
		 'OS', 'IR', 'PT', 'AU', 'HG', 'TL', 'PB', 'BI', 'PO', 'AT', 'RN', 'FR', 'RA', 'AC', 'TH', 'PA', 'U', 'NP',
		 'PU', 'AM', 'CM', 'BK', 'CF', 'ES', 'FM', 'MD', 'NO', 'LR', 'RF', 'DB', 'SG', 'BH', 'HS', 'MT', 'DS', 'RG',
		 'CN', 'NH', 'FL', 'MC', 'LV', 'TS', 'OG']

		mols = []
		u = mda.Universe(traj_file, top_file)
		hbonds_df = pd.DataFrame()
		for seg in u.segments:
			if 'PRO' not in str(seg) and str(seg)[1:-1].split(' ')[1].split('_')[2] not in solvent_mol and \
					str(seg)[1:-1].split(' ')[1].split('_')[2] not in ions and 'DNA' not in str(seg):
				df = pd.DataFrame()
				hbonds = HydrogenBondAnalysis(universe=u, d_a_cutoff=3.6, update_selections=False)
				hbonds.hydrogens_sel = hbonds.guess_hydrogens("protein")
				hbonds.acceptors_sel = hbonds.guess_acceptors("segid " + str(seg)[1:-1].split(' ')[1])
				hbonds.run(verbose=True)
				df1 = pd.DataFrame(hbonds.times, columns=['Time (ns)'])
				df2 = pd.DataFrame(hbonds.count_by_time(), columns=[str(top_file).split('.')[0] + ' ' +
																	str(seg)[1:-1].split(' ')[1].split('_')[2]])
				df = pd.concat([df1, df2], axis=1)
				df.to_csv(str(seg)[1:-1].split(' ')[1].split('_')[2] + '_hbonds.csv')
				hbonds_df = pd.concat([hbonds_df, df], axis=1)
			if 'DNA' in str(seg) and 'DNA' not in mols:
				mols.append('DNA')
		if 'DNA' in mols:
			mols.append(str(seg)[1:-1].split(' ')[1].split('_')[2])
			hbonds = HydrogenBondAnalysis(universe=u, d_a_cutoff=3.6, update_selections=False)
			hbonds.hydrogens_sel = hbonds.guess_hydrogens("protein")
			hbonds.acceptors_sel = hbonds.guess_acceptors("nucleic")
			hbonds.run(verbose=True)
			df1 = pd.DataFrame(hbonds.times, columns=['Time (ns)'])
			df2 = pd.DataFrame(hbonds.count_by_time(), columns= [str(top_file).split('.')[0] +  str(' DNA ')])
			dna_df = pd.concat([df1, df2], axis=1)
			dna_df.to_csv('DNA_hbonds.csv')
			if hbonds_df.empty:
				hbonds_df = pd.concat([hbonds_df, dna_df], axis=1)
			else:
				hbonds_df = pd.merge(hbonds_df, dna_df, on='Time (ns)', how='inner')
		return hbonds_df

	def hbond_comp(self, traj_folder, output_dir):
		"""This fucntion iterates through each of the systems that were simulated and calls the hbonds
		function to determine the respective contacts. Each of the hbonds for each of the systems under
		investigation have their hbonds.csv retrieved and each of the columns at the respective positions
		(each column correlates to the same molecule investigated) and appended to a new dataframe for ease of
		comparison between the systems, which is then stored in the output specified folder."""
		df = pd.DataFrame()
		for folder in os.listdir(traj_folder):
			top_file = ''
			traj_file = ''
			os.chdir('{0}\{1}'.format(str(traj_folder), folder))
			for file in os.listdir():
				if file.endswith('.xtc') and 'rmsfit_' not in str(file):
					traj_file = file
				elif file.endswith('.tpr'):
					top_file = file
			sys_hbonds = self.hbond_calc(traj_file, top_file)
			sys_hbonds.to_csv(str(top_file).split('.')[0] + '_sys_hbonds.csv')
			print(sys_hbonds)
		df_len = ''
		counter = 2
		for folder2 in os.listdir(traj_folder):
			os.chdir('{0}\{1}'.format(str(traj_folder), folder2))
			for file in os.listdir():
				if file.endswith('_sys_hbonds.csv'):
					df = pd.read_csv(file)
					df = df.iloc[:,1:len(df)]
					df_len = len(df.columns)
		while counter <= df_len:
			df_hbond = pd.DataFrame()
			for folder2 in os.listdir(traj_folder):
				os.chdir('{0}\{1}'.format(str(traj_folder), folder2))
				for file in os.listdir():
					if file.endswith('_sys_hbonds.csv'):
						df = pd.read_csv(file)
						df_hbond = pd.concat([df_hbond, df.iloc[:,counter]], axis=1)
			counter += 1
			os.chdir(output_dir)
			df_hbond.to_csv(str(counter-2) + '_multi_variant_hbonds.csv')

	def single_hbonds_plots(self, traj_folder, outputs_dir):
		"""This function plots the hbonds.csv file generated by the hbonds function from within the previously defined
		system directory and creates a figure with the dataset present within the file. This was included along with the
		option to have multiple plots on a single set of axes as it became difficult to interpret the results with the
		more systems present."""
		counter = 0
		for folder in os.listdir(traj_folder):
			os.chdir('{0}\{1}'.format(str(traj_folder), folder))
			for file in os.listdir():
				df = pd.DataFrame()
				if file.endswith('_hbonds.csv') and 'sys' not in str(file):
					hb_df = pd.read_csv(file)
					hb_df['Time (ns)'] = hb_df['Time (ns)']/1000
					df = pd.concat([df, hb_df.iloc[:,1:3]], axis =1)
					df.plot(x='Time (ns)')
					plt.ylabel(r"$N_{HB}$")
					plt.title('No. of H-bonds between Protein and ' + str(file).split('.')[0].split('_')[0] +
							  ' within ' + str(folder))
					plt.savefig('{0}\{1}_{2}{3}'.format(str(outputs_dir), str(folder), str(file).split('.')[0],
														 '.tiff'),
								bbox_inches='tight', dpi=600)


	def multi_hbonds_plots(self, outputs_dir):
		"""This function plots the 'multi-variant_hbonds'.csv file generated by the hbonds_comp function from within the
		previously defined output directory and creates a figure with each dataset present within the file. This
		function was developed prior to the single plot generation, however too many datasets resulted in degraded
		visualization."""
		os.chdir(outputs_dir)
		for file in os.listdir(outputs_dir):
			if file.endswith('multi_variant_hbonds.csv'):
				hb_df = pd.read_csv(file)
				hb_df['Unnamed: 0'] = hb_df['Unnamed: 0']/100
				hb_df.rename(columns = {'Unnamed: 0':'Time (ns)'}, inplace=True)
				hb_df.plot(x='Time (ns)', linewidth = 0.75)
				plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
				plt.ylabel(r"$N_{HB}$")
				plt.title(
					'No. of H-bonds within multiple systems')
				plt.savefig('{0}\{1}{2}'.format(str(outputs_dir), str(file).split('.')[0], '_multi_hbonds.tiff'), bbox_inches='tight', dpi=600)

def main(systems, output_dir):
	p = Contacts()
	#p.saltbridges_comp(systems, output_dir)
	#p.single_sb_plotting(systems, output_dir)
	#p.multi_sb_plotting(output_dir)
	#p.hbond_comp(systems, output_dir)
	p.single_hbonds_plots(systems, output_dir)
	#p.multi_hbonds_plots(output_dir)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--systems", help="Path to the trajectory files have been simulated. ")
    parser.add_argument("--output_dir", help="Path to the directory that the variant systems will be stored in")
    args = parser.parse_args()
    systems = str(args.systems)
    output_dir = str(args.output_dir)
    main(systems, output_dir)